### PR TITLE
Use asyncio to block forever rather than time sleep

### PR DESCRIPTION
**Pull request by trajano**
https://stackoverflow.com/questions/78465203/internally-is-asyncio-run-forever-basically-a-while-true-loop/78465221#78465221

https://stackoverflow.com/a/78463084/242042

### CODE REVIEW

**Comment by spyoungtech** [comment]
Thanks for raising this. However, all code in the `_sync` directory is automatically generated. Changes to `_sync/`  must originate from `_async/` changes.

**Comment by trajano** [comment]
> Thanks for raising this. However, all code in the `_sync` directory is automatically generated. Changes to `_sync/` must originate from `_async/` changes.

Oof that's probably why when I use the requirements.txt to point to my git repo my changes are not being reflected and I was wondering WTF... because this is the second one I am doing patch work for my weekend project https://github.com/jath03/openrgb-python/pull/72 was the first and it seemed to work.

**Comment by trajano** [comment]
BTW if `_sync` is generated why is the source present in the repo?

**Comment by spyoungtech** [comment]
It perhaps doesn't _have_ to be committed, and I've gone back and forth on whether it should be or not, but ultimately it made it easier for linting tools, mypy, sphinx/readthedocs, etc. to all work correctly and allows someone to see the source online like, say, if they're investigating a stacktrace that points to a line in the `_sync` code.

**Pull request closed without merging**
