### PR TITLE
Adding Window.click functionality - using ControlClick

### PR DESCRIPTION
**Pull request by DizzyThermal**
`Window.click(x, y)`
https://www.autohotkey.com/docs/commands/ControlClick.htm

### CODE REVIEW

**Comment by DizzyThermal** [comment]
I ran a `pip install .` after cleaning my site-package to ensure it was working in my use case. It clicks the desired x, y location using ControlClick in an out-of-focus window :)

**Comment by spyoungtech** [comment]
Hey Dizzy, thanks for making this PR. I'm pretty unavailable this week, but wanted to let you know I should be able to get around to reviewing these this weekend.

**Comment by spyoungtech** [comment]
Looks good to me. I'll merge this in and it should end up in the next release :)

**Comment by spyoungtech** [comment]
Released in v0.9.0 🎉

**Pull request merged**
